name: Request input information
 
on:
  workflow_dispatch:
    inputs:
      mensagem:
        type: string
        description: Coloque aqui a mensagem
        required: true
      sql-command:  # Verifique se está sendo fornecido corretamente
        type: string
        description: Coloque aqui SQL a ser executado
        required: true
      ambiente:
        type: environment
      nuvem:
        type: choice
        description: Escolha o SGBD para deploy
        options:
        - SqlServer
        - Oracle
        - Postgres
        - MariaDB
      agreement:
        type: boolean
        description: Concorda com os termos

jobs:
  teste-postgres-sql:
    if: ${{ github.event.inputs.nuvem == 'Postgres' }} 
    uses: ./.github/workflows/postgres.yml
    with:
      config-path: "Postgres"
      repo-token: "hello"
    secrets:
      SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
  teste-oracle-sql:
    if: ${{ github.event.inputs.nuvem == 'Oracle' }} 
    uses: ./.github/workflows/oracle.yml
    with:
      config-path: "Oracle"
      repo-token: "hello"
    secrets:
      SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}

