name: POSTGRES DOCKER

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: postgres:16
      env:
        NODE_ENV: features
        POSTGRES_PASSWORD: Abcd1234
        POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      ports:
        - 5432
      volumes:
        - dados:/mnt
      options: --cpus 1

    steps:
      - uses: actions/checkout@v2

      - name: Wait for PostgreSQL to start
        run: |
          until pg_isready; do
            echo "Waiting for PostgreSQL to start..."
            sleep 2
          done

      - name: Run a one-line script inside the container
        run: ls -all

      - name: Run a multi-line script
        run: |
          cat /etc/postgresql/16/main/pg_hba.conf
          psql -U postgres -c '\l'

