name: POSTGRES DOCKER

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: postgres:16
      env:
        NODE_ENV: features
        POSTGRES_PASSWORD: Abcd1234
        POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      ports:
        - 5432
      volumes:
        - dados:/mnt
      options: --cpus 1

    steps:
      - uses: actions/checkout@v2

      - name: Listar arquivos no contêiner
        run: ls -all

      - name: Verificar processos em execução
        run: |
          echo "Verificando processos em execução..."
          pgrep postgres

      - name: Esperar pelo PostgreSQL iniciar
        run: |
          until pg_isready -h localhost; do
            echo "Waiting for PostgreSQL to start..."
            sleep 2
          done

      - name: Verificar logs do PostgreSQL
        run: |
          echo "PostgreSQL logs:"
          cat /var/lib/postgresql/data/log/postgresql.log

      - name: Executar script multi-linhas
        run: |
          cat /var/lib/postgresql/data/pg_hba.conf
          psql -U postgres -c '\l'



